 [[language]]
 name = "typescript"
 language-servers = [ "typescript-language-server", "tailwindcss-language-server", "biome"]
 formatter = { command = "biome", args = ["format", "--stdin-file-path"]}
 indent = { tab-width = 2, unit = " " }
 auto-format = true

 [[language]]
 name = "tsx"
 language-servers = [ "typescript-language-server", "tailwindcss-language-server", "biome"]
 formatter = { command = "biome", args = ["format", "--stdin-file-path"]}
 indent = { tab-width = 2, unit = " " }
 auto-format = true

 [[language]]
 name = "jsx"
 language-servers = [ "typescript-language-server", "tailwindcss-language-server", "biome"]
 grammar = "javascript"
 formatter = { command = "biome", args = ["format", "--stdin-file-path"]}
 indent = { tab-width = 2, unit = " " }
 auto-format = true

 [[language]]
 name = "javascript"
 language-servers = [ "typescript-language-server", "tailwindcss-language-server", "biome"]
 formatter = { command = "biome", args = ["format", "--stdin-file-path"]}
 indent = { tab-width = 2, unit = " " }
 auto-format = true

 # [[language]]
 # name = "json"
 # language-servers = [ "vscode-json-language-server" ]
 # formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }
 # indent = { tab-width = 2, unit = "\t" }
 # auto-format = true

 # [language-server.vscode-json-language-server.config]
 # json = { validate = { enable = true }, format = { enable = true } }
 # provideFormatter = true

 # [language-server.vscode-css-language-server.config]
 # css = { validate = { enable = true } }
 # scss = { validate = { enable = true } }
 # less = { validate = { enable = true } }
 # provideFormatter = true

 # [[language]]
 # name = "html"
 # formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }
 # language-servers = [ "vscode-html-language-server", "tailwindcss-react"]
 
 # [[language]]
 # name = "css"
 # formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }
 # language-servers = [ "vscode-css-language-server", "tailwindcss-react"]

 # [language-server.eslint]
 # args = ["--stdio"]
 # command = "vscode-eslint-language-server"

[language-server]
tailwindcss-language-server = { command = "tailwindcss-language-server", args = ["stdio"]}
biome = { command = "biome", args = ["lsp-proxy"] }
