[tools]
1password-cli = "latest"
node = "18"
terraform = "latest"
minikube = "latest"
kubectl = "latest"
k9s = "latest"
github-cli = "latest"
eksctl = "latest"
awscli = "latest"
pnpm = "latest"
bun = "latest"
argocd = "latest"
bottom = "latest"
lazygit = "latest"
helm = "latest"
aws-iam-authenticator = "latest"
cloudflared = "latest"
pkl = "latest"
rust = "latest"
pulumi = "latest"
neovim = "latest"

[settings]
experimental = true
